# Wren AI Service Configuration
app:
  host: "0.0.0.0"
  port: 8000
  log_level: "DEBUG"

# LLM Configuration
type: llm
provider: litellm_llm
models:
  - api_base: "http://host.docker.internal:11434/v1"
    model:ollama_chat/gemma3:1b
    timeout: 120
  

# Embedding Configuration  
type: embedder
provider: litellm_embedder
models: 
  - model: ollama/nomic-embed-text
    api_base: "http://host.docker.internal:11434/v1"
    timeout: 120
    # dimension: 3072

# Vector Database
vector_store:
  provider: "qdrant"
  url: "http://qdrant:6333"
  collection_name: "wren_vectors"
  api_key: ""

# Engine Configuration
engine:
  endpoint: "http://wren-engine:5555"

# Database Configuration
database:
  type: "mysql"
  host: "wren-mysql"
  port: 3306
  user: "wren"
  password: "1376"
  database: "wrenai"